---
development:
  dialect: postgres
  database: coke_development
  user: postgres
  password: endava
  host: localhost
  pool: 5
  port: 5433

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/products_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/products_production?sslmode=disable"}}
